rift_zones = [
        'Blue Side Raptor Brush',
        'Blue Side Raptors (Inner)',
        'Blue Side Raptors (Outer)',
        'Blue Side Raptor Intersection',
        'Blue Side Raptor Ramp Entrance',
        'Behind Dragon Pit 1',
        'Behind Dragon Pit 2',
        'Blue Side Red Brush',
        'Blue Side Red Ramp Brush',
        'Blue Side Red Buff 1',
        'Blue Side Red Buff 2',
        'Blue Side Krugs Intersection Brush',
        'Blue Side Krugs Intersection 2',
        'Blue Side Krugs Intersection 1',
        'Blue Side Krugs',
        'Blue Side Krugs Brush',
        'Blue Side Red Shallow Cross',
        'Blue Side Red Gate Brush',
        'Blue Side Red Gate',
        'Blue Side Red Gate',
        'Blue Side Red Deep Path',
        'Blue Side Red Deep Cross',
        'Blue Side Red Dive Area',
        'Blue Side Red Tribrush',
        'Blue Side Wolves Ramp Brush',
        'Blue Side Wolves Ramp',
        'Blue Side Wolves Intersection 1',
        'Blue Side Wolves Intersection 2',
        'Blue Side Wolves Brush',
        'Blue Side Blue Deep Cross',
        'Blue Side Wolves',
        'Blue Side Blue Intersection 1',
        'Blue Side Blue Intersection 2',
        'Blue Side Blue Gate',
        'Blue Side Blue Buff',
        'Blue Side Gromp',
        'Blue Side Blue Tribrush',
        'Blue Side Blue Pocket',
        'Blue Side Blue Ramp Brush',
        'Blue Side Blue Ramp',
        'Blue Side Blue Shallow Cross',
        'Red Side Raptor Brush',
        'Red Side Raptors (Inner)',
        'Red Side Raptors (Outer)',
        'Red Side Raptor Intersection',
        'Red Side Raptor Ramp Entrance',
        'Behind Baron Pit 1',
        'Behind Baron Pit 2',
        'Red Side Red Brush',
        'Red Side Red Ramp Brush',
        'Red Side Red Buff 1',
        'Red Side Red Buff 2',
        'Red Side Krugs Intersection Brush',
        'Red Side Krugs Intersection 1',
        'Red Side Krugs Intersection 2',
        'Red Side Krugs',
        'Red Side Krugs Brush',
        'Red Side Red Shallow Cross',
        'Red Side Red Gate Brush',
        'Red Side Red Gate 1',
        'Red Side Red Gate 2',
        'Red Side Red Deep Path',
        'Red Side Red Deep Cross',
        'Red Side Red Dive Area',
        'Red Side Red Tribrush',
        'Red Side Wolves Ramp Brush',
        'Red Side Wolves Ramp',
        'Red Side Wolves Intersection 1',
        'Red Side Wolves Intersection 2',
        'Red Side Wolves Brush',
        'Red Side Blue Deep Cross',
        'Red Side Wolves',
        'Red Side Blue Intersection 1',
        'Red Side Blue Intersection 2',
        'Red Side Blue Gate',
        'Red Side Blue Buff',
        'Red Side Gromp',
        'Red Side Blue Tribrush',
        'Red Side Blue Pocket',
        'Red Side Blue Ramp Brush',
        'Red Side Blue Ramp',
        'Red Side Blue Shallow Cross',
        'Bot Line Brush',
        'Bot Mid River 1',
        'Bot Mid River 2',
        'Bot Pixel',
        'Dragon Pit',
        'Outside Dragon Pit (Higher)',
        'Outside Dragon Pit (Lower)',
        'Bot River Brush',
        'Bot Tribrush Entrance',
        'Bot River Mouth 1',
        'Bot River Mouth 2',
        'Top Line Brush',
        'Top Mid River 1',
        'Top Mid River 2',
        'Top Pixel',
        'Baron Pit',
        'Outside Baron Pit (Lower)',
        'Outside Baron Pit (Higher)',
        'Top River Brush',
        'Top Tribrush Entrance',
        'Top River Mouth 1',
        'Top River Mouth 2',
        'Mid Lane (Center)',
        'Blue Side Mid Outer Tower',
        'Blue Side Mid Outside Outer Tower',
        'Blue Side Mid Inner Tower',
        'Blue Side Mid Cross',
        'Red Side Mid Outer Tower',
        'Red Side Mid Outside Outer Tower',
        'Red Side Mid Inner Tower',
        'Red Side Mid Cross',
        'Bot Lane Brush Middle',
        'Bot Lane Brush Left',
        'Bot Lane Brush Right',
        'Bot Lane (Center) 1',
        'Bot Lane (Center) 2',
        'Bot Lane (Center) 3',
        'Bot Lane Alcove',
        'Blue Side Bot Lane Outer Tower',
        'Blue Side Bot Lane Outside Outer Tower',
        'Blue Side Bot Lane Inner Tower',
        'Blue Side Bot Lane Area',
        'Red Side Bot Lane Outer Tower',
        'Red Side Bot Lane Outside Outer Tower',
        'Red Side Bot Lane Inner Tower',
        'Red Side Bot Lane Area',
        'Top Lane Brush Middle',
        'Top Lane Brush Right',
        'Top Lane Brush Left',
        'Top Lane (Center) 1',
        'Top Lane (Center) 2',
        'Top Lane (Center) 3',
        'Top Lane Alcove',
        'Red Side Top Lane Outer Tower',
        'Red Side Top Lane Outside Outer Tower',
        'Red Side Top Lane Inner Tower',
        'Red Side Top Lane Area',
        'Blue Side Top Lane Outer Tower',
        'Blue Side Top Lane Outside Outer Tower',
        'Blue Side Top Lane Inner Tower',
        'Blue Side Top Lane Area',
        'Blue Side Base',
        'Blue Side Top Inhib Entrance',
        'Blue Side Mid Inhib Entrance',
        'Blue Side Bot Inhib Entrance',
        'Red Side Base',
        'Red Side Top Inhib Entrance',
        'Red Side Mid Inhib Entrance',
        'Red Side Bot Inhib Entrance',
    ]